server:
  port: 8080
spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myweb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=America/New_York
    username: root
    password: root
